[Feature] expand naming convention
mediamonks/eslint-config pull request #29
Opened 2022-03-16 18:07 UTC by psimk

> permit exported variables to be `StrictPascalCase`

Our component names across frameworks are in `PascalCase`, and as we generally write one component per file, they are immediately exported. So it makes sence IMO, to permit exported variables to be `StrictPascalCase`.

> permit any format for object literal properties

The current setup makes it really annoying to code HTML element attributes, which we often do in Muban.

_example:_
```js
attr: {
  'aria-expanded': ...,
  'aria-disabled': ...,
}
```

I think it is completely reasonable to permit any format for object literal properties. As the only time where we will actually use them is when the keys of the object in question are not known i.e. `Record<string, ...>`. So in cases like above in Muban, or handling API data - all cases that we can't control.

2022-03-16 21:59 UTC, ThaNarie commented
> I think it is completely reasonable to permit any format for object literal properties.

Not that I'm against, but this would also allow the highly debated:

```js
const foo = {
  FOO: 'abc',
  BAR: 'def',
}
```

right?

2022-03-16 21:59 UTC, ThaNarie approved these changes

2022-03-17 09:07 UTC, psimk commented
@ThaNarie 
> this would also allow the highly debated:
> ```js
> const foo = {
>  FOO: 'abc',
>  BAR: 'def',
>}
>```

we can also permit all formats, except for `UPPER_CASE`, so this casing would not be permitted.

2022-03-17 12:30 UTC, ThijsTyZ commented
> @ThaNarie
> 
> > this would also allow the highly debated:
> > ```js
> > const foo = {
> >  FOO: 'abc',
> >  BAR: 'def',
> > }
> > ```
> 
> we can also permit all formats, except for `UPPER_CASE`, so this casing would not be permitted.

I agree we should allow:
```
attr: {
  'aria-expanded': ...,
  'aria-disabled': ...,
}
```

However we should not allow
```
const foo = {
 FOO: 'abc',
 BAR: 'def',
}
```

So it would be nice if we can prevent that

2022-03-17 12:31 UTC, ThijsTyZ requested changes
We should disallow
```
const foo = {
 FOO: 'abc',
 BAR: 'def',
}
```

2022-03-17 12:47 UTC, psimk commented
@ThaNarie @ThijsTyZ 
I updated the rule to something better: it will disallow all formats except `strictCamelCase` as before, except for quoted properties - which is exactly what we want.

> ❌
```ts
const foo = {
 FOO: 'abc',
 BAR: 'def',
}
```

> :heavy_check_mark: 
```ts
const foo = {
 'foo-bar': 'abc',
 'bar-foo': 'def',
}
```

2022-03-17 12:51 UTC, ThaNarie approved these changes

2022-03-17 13:44 UTC, ThijsTyZ approved these changes

2022-03-17 14:14 UTC, merged